name: use-random
version: 0.1.0.0
github: "H1rono/sandbox.hs"
license: BSD-3-Clause
author: "H1rono"
maintainer: "hronok66@gmail.com"
copyright: "2026 H1rono"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/H1rono/sandbox.hs/tree/main/use-random#readme>

dependencies:
  - base >= 4.7 && < 5
  - random >= 1 && < 2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  random_string:
    main: Main.hs
    source-dirs: app/random_string
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - use-random

tests:
  use-random-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - use-random
